#!/bin/bash
# Auto-generate CHANGELOG.md from git history
# Usage: ./changelog.sh

set -e

LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
HEAD_COMMIT=$(git rev-parse --short HEAD)
DATE=$(date +%Y-%m-%d)

if [ -n "$LATEST_TAG" ]; then
    COMMITS=$(git log "$LATEST_TAG"..HEAD --pretty=format:"%H|%s|%an|%ad" --date=short)
    RANGE="since $LATEST_TAG"
else
    COMMITS=$(git log --pretty=format:"%H|%s|%an|%ad" --date=short -n 50)
    RANGE="last 50 commits"
fi

# Categorize function
categorize() {
    local msg="$1"
    local lower=$(echo "$msg" | tr "[:upper:]" "[:lower:]")
    case "$lower" in
        *feat*|*add*|*new*|*introduce*|*implement*|*create*|*support*) echo "Added" ;;
        *fix*|*bug*|*repair*|*resolve*|*patch*|*correct*|*hotfix*) echo "Fixed" ;;
        *remove*|*delete*|*drop*|*deprecat*|*clean*|*purge*) echo "Removed" ;;
        *change*|*update*|*refactor*|*rework*|*modify*|*improve*|*enhance*|*optim*) echo "Changed" ;;
        *) echo "Changed" ;;
    esac
}

# Build CHANGELOG
{
    echo "# Changelog"
    echo ""
    echo "All notable changes to this project will be documented in this file."
    echo ""
    echo "## [Unreleased] - $DATE"
    echo ""
    echo "**Commit range:** $RANGE"
    echo ""
    echo "**Latest commit:** $HEAD_COMMIT"
    echo ""

    ADDED=""
    FIXED=""
    CHANGED=""
    REMOVED=""

    while IFS="|" read -r hash subject author date; do
        [ -z "$subject" ] && continue
        category=$(categorize "$subject")
        line="- $subject"

        case "$category" in
            "Added") ADDED="$ADDED$line\n" ;;
            "Fixed") FIXED="$FIXED$line\n" ;;
            "Changed") CHANGED="$CHANGED$line\n" ;;
            "Removed") REMOVED="$REMOVED$line\n" ;;
        esac
    done <<< "$COMMITS"

    if [ -n "$ADDED" ]; then
        echo "### Added"
        printf "%b" "$ADDED"
        echo ""
    fi

    if [ -n "$FIXED" ]; then
        echo "### Fixed"
        printf "%b" "$FIXED"
        echo ""
    fi

    if [ -n "$CHANGED" ]; then
        echo "### Changed"
        printf "%b" "$CHANGED"
        echo ""
    fi

    if [ -n "$REMOVED" ]; then
        echo "### Removed"
        printf "%b" "$REMOVED"
        echo ""
    fi

    echo "---"
    echo "Generated by changelog.sh on $DATE"
} > CHANGELOG.md

echo "CHANGELOG.md generated successfully!"