#!/usr/bin/env python3
"""Claude Code PR Review Agent — analyzes a PR and outputs structured Markdown review."""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

def run_gh(args):
    cmd = ["gh", "api"] + args
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    return json.loads(result.stdout)

def parse_pr_url(url):
    m = re.match(r"https://github\.com/([^/]+)/([^/]+)/pull/(\d+)", url)
    if not m:
        print("Invalid PR URL format", file=sys.stderr)
        sys.exit(1)
    return m.group(1), m.group(2), m.group(3)

def get_pr_info(owner, repo, pr_number):
    return run_gh([f"repos/{owner}/{repo}/pulls/{pr_number}"])

def get_pr_diff(owner, repo, pr_number):
    cmd = ["gh", "api", f"repos/{owner}/{repo}/pulls/{pr_number}", "--jq", ".body"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.stdout

def get_pr_files(owner, repo, pr_number):
    return run_gh([f"repos/{owner}/{repo}/pulls/{pr_number}/files"])

def analyze_pr(pr_info, files):
    title = pr_info.get("title", "")
    body = pr_info.get("body", "") or ""> No description provided."
    additions = pr_info.get("additions", 0)
    deletions = pr_info.get("deletions", 0)
    changed_files = pr_info.get("changed_files", 0)

    # Identify risks
    risks = []
    suggestions = []
    has_tests = False
    has_docs = False
    has_sensitive = False

    sensitive_patterns = [".env", "config", "secret", "password", "token", "key", "auth"]
    for f in files:
        filename = f.get("filename", "")
        if any(p in filename.lower() for p in sensitive_patterns):
            has_sensitive = True
        if "test" in filename.lower():
            has_tests = True
        if "readme" in filename.lower() or "doc" in filename.lower():
            has_docs = True
        if f.get("status") == "removed":
            risks.append(f"File deleted: {filename}")
        if f.get("additions", 0) > 500:
            suggestions.append(f"Consider splitting {filename} — large addition (+{f['additions']} lines)")

    if has_sensitive:
        risks.append("Sensitive files modified — review for leaked credentials")
    if not has_tests and changed_files > 2:
        suggestions.append("Add tests for new functionality")
    if not has_docs and changed_files > 3:
        suggestions.append("Update documentation/README for significant changes")
    if deletions > additions * 2:
        risks.append("High deletion ratio — verify no critical code removed")

    # Confidence score
    risk_count = len(risks)
    if risk_count == 0:
        confidence = "High"
    elif risk_count <= 2:
        confidence = "Medium"
    else:
        confidence = "Low"

    return {
        "title": title,
        "body": body,
        "additions": additions,
        "deletions": deletions,
        "changed_files": changed_files,
        "risks": risks,
        "suggestions": suggestions,
        "confidence": confidence,
    }

def generate_review(analysis):
    lines = [
        "## PR Review Summary",
        "",
        f"**Changes:** {analysis['changed_files']} files (+{analysis['additions']} / -{analysis['deletions']})",
        "",
        "### Summary",
        f"This PR modifies {analysis['changed_files']} files with {analysis['additions']} additions and {analysis['deletions']} deletions.",
        "",
        "### Identified Risks",
    ]
    if analysis["risks"]:
        for risk in analysis["risks"]:
            lines.append(f"- ⚠️ {risk}")
    else:
        lines.append("- No significant risks identified.")
    lines += [
        "",
        "### Improvement Suggestions",
    ]
    if analysis["suggestions"]:
        for s in analysis["suggestions"]:
            lines.append(f"- 💡 {s}")
    else:
        lines.append("- No suggestions at this time.")
    lines += [
        "",
        f"### Confidence Score: {analysis['confidence']} ",
        "",
        "---",
        "*Generated by claude-review*",
    ]
    return "
".join(lines)

def main():
    parser = argparse.ArgumentParser(description="Review a GitHub PR")
    parser.add_argument("--pr", required=True, help="PR URL (https://github.com/owner/repo/pull/123)")
    args = parser.parse_args()

    owner, repo, pr_number = parse_pr_url(args.pr)
    pr_info = get_pr_info(owner, repo, pr_number)
    files = get_pr_files(owner, repo, pr_number)
    analysis = analyze_pr(pr_info, files)
    review = generate_review(analysis)
    print(review)

if __name__ == "__main__":
    main()